import { useMemo, useState } from "react";
import { ArrowUpRight, Check, Coins, Copy, ExternalLink, Gift, LockKeyhole, ShieldCheck, Sparkles, WalletCards } from "lucide-react";
import VelvetNav from "@/components/VelvetNav";
import { toast } from "sonner";

const DEXSCREENER = "https://dexscreener.com/polygon/0x04c3be465e530b0a7617b197a91fcd990154027f";
const activity = [["Racconto pubblicato", "+420 DSN", "Creator pool · verificato"], ["Ascolto qualificato", "+38 DSN", "Community pool · maturato"], ["Invito membro", "+120 DSN", "Creator pool · in attesa"], ["Feedback editoriale", "+24 DSN", "Community pool · maturato"]];

export default function Rewards() {
  const [wallet, setWallet] = useState("");
  const [walletSaved, setWalletSaved] = useState(false);
  const [activeTab, setActiveTab] = useState<"creator" | "community">("creator");
  const [claimed, setClaimed] = useState(false);
  const [copied, setCopied] = useState(false);
  const total = activeTab === "creator" ? 1840 : 790;
  const pending = activeTab === "creator" ? 310 : 80;
  const share = activeTab === "creator" ? "70%" : "30%";
  const progress = useMemo(() => Math.min(100, Math.round((total / 3000) * 100)), [total]);
  const saveWallet = () => { const normalized = wallet.trim(); if (!/^0x[a-fA-F0-9]{40}$/.test(normalized)) { toast.error("Inserisci un indirizzo wallet Polygon valido"); return; } setWalletSaved(true); toast.success("Wallet salvato", { description: "Sarà usato solo come destinazione del payout, mai come custodia." }); };
  const copyToken = async () => { await navigator.clipboard?.writeText(DEXSCREENER); setCopied(true); toast("Link DSN copiato"); setTimeout(() => setCopied(false), 1800); };
  return <div className="velvet-shell min-h-screen"><VelvetNav /><main className="container py-12 md:py-16">
    <section className="grid gap-8 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><div><p className="section-kicker">Red Velvet / DSN Farm</p><h1 className="display-font mt-3 text-5xl leading-[.98] text-white md:text-7xl">Il tuo ritmo<br /><span className="text-[#d7b46a]">coltiva valore.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#c8bdc8]">Una farm interna che riconosce il lavoro dei creator e la presenza della community. Prima punti e maturazione trasparente; poi payout DSN non-custodial, dopo i controlli necessari.</p></div><div className="rounded-3xl border border-[#d7b46a]/25 bg-[#190e22] p-6"><div className="flex items-center justify-between"><div><p className="section-kicker">Riferimento $DSN</p><p className="mt-2 text-2xl font-black text-white">Polygon · Dexscreener</p><p className="mt-1 text-xs text-[#a99aa7]">Link fornito dall’operatore; non è una prova di rendimento o di payout.</p></div><Coins className="text-[#d7b46a]" size={26} /></div><div className="mt-5 flex flex-wrap gap-2"><button onClick={copyToken} className="flex items-center gap-2 rounded-full border border-white/15 px-3 py-2 text-[11px] font-extrabold text-[#f1d58f]">{copied ? <Check size={13} /> : <Copy size={13} />} {copied ? "Copiato" : "Copia link DSN"}</button><a href={DEXSCREENER} target="_blank" rel="noreferrer" className="flex items-center gap-2 rounded-full border border-white/15 px-3 py-2 text-[11px] font-extrabold text-white">Apri Dexscreener <ExternalLink size={13} /></a></div></div></section>
    <section className="mt-10 grid gap-4 md:grid-cols-4"><div className="rounded-2xl border border-white/10 bg-[#120b19] p-5"><p className="section-kicker">Saldo maturato</p><p className="mt-2 text-3xl font-black text-white">{total.toLocaleString("it-IT")} <span className="text-sm text-[#d7b46a]">DSN</span></p><p className="mt-2 text-xs text-[#a99aa7]">Attribuito alla tua attività</p></div><div className="rounded-2xl border border-white/10 bg-[#120b19] p-5"><p className="section-kicker">In attesa</p><p className="mt-2 text-3xl font-black text-white">{pending} <span className="text-sm text-[#d7b46a]">DSN</span></p><p className="mt-2 text-xs text-[#a99aa7]">Finestra anti-abuso</p></div><div className="rounded-2xl border border-white/10 bg-[#120b19] p-5"><p className="section-kicker">Quota pool</p><p className="mt-2 text-3xl font-black text-white">{share}</p><p className="mt-2 text-xs text-[#a99aa7]">{activeTab === "creator" ? "Creator pool" : "Community pool"}</p></div><div className="rounded-2xl border border-[#d7b46a]/25 bg-[#190e22] p-5"><p className="section-kicker">Stato payout</p><p className="mt-2 flex items-center gap-2 text-lg font-black text-[#f1d58f]"><LockKeyhole size={17} /> In preparazione</p><p className="mt-2 text-xs leading-5 text-[#a99aa7]">Nessun trasferimento automatico attivo.</p></div></section>
    <section className="mt-8 rounded-3xl border border-[#d7b46a]/20 bg-[#190e22] p-6 md:p-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-start"><div><div className="flex items-center gap-3"><Sparkles className="text-[#d7b46a]" size={20} /><div><p className="section-kicker">Farm allocation</p><h2 className="mt-1 text-2xl font-extrabold text-white">Creator prima, community sempre.</h2></div></div><p className="mt-4 max-w-2xl text-sm leading-6 text-[#c0afcb]">La proposta iniziale destina il 70% degli incentivi alle persone che producono valore editoriale e il 30% a chi legge, ascolta, partecipa e fa crescere il club. La percentuale è configurabile prima dell'attivazione on-chain.</p></div><div className="flex rounded-full border border-white/10 bg-black/20 p-1"><button onClick={() => setActiveTab("creator")} className={`rounded-full px-4 py-2 text-xs font-extrabold ${activeTab === "creator" ? "bg-[#d7b46a] text-[#09070d]" : "text-[#b9a9b5]"}`}>Creator 70%</button><button onClick={() => setActiveTab("community")} className={`rounded-full px-4 py-2 text-xs font-extrabold ${activeTab === "community" ? "bg-[#d7b46a] text-[#09070d]" : "text-[#b9a9b5]"}`}>Utenti 30%</button></div></div><div className="mt-7 h-3 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-[#5c1a1b] via-[#a86558] to-[#d7b46a]" style={{ width: activeTab === "creator" ? "70%" : "30%" }} /></div><div className="mt-3 flex justify-between text-[10px] font-extrabold uppercase tracking-[.14em] text-[#9d8dac]"><span>Pool creator 70%</span><span>Pool community 30%</span></div><div className="mt-6 grid gap-3 md:grid-cols-4">{[["Pubblica", "+420 DSN", "Creator"], ["Ascolta", "+20 DSN", "Utente"], ["Invita", "+120 DSN", "Entrambi"], ["Cura", "+60 DSN", "Moderazione"]].map(([title, amount, label]) => <div key={title} className="rounded-2xl border border-white/10 bg-black/10 p-4"><p className="text-sm font-extrabold text-white">{title}</p><p className="mt-2 text-xl font-black text-[#d7b46a]">{amount}</p><p className="mt-1 text-[10px] uppercase tracking-[.12em] text-[#9d8dac]">{label}</p></div>)}</div></section>
    <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_380px]"><section className="rounded-3xl border border-white/10 bg-[#120b19] p-6 md:p-8"><div className="flex items-center justify-between"><div><p className="section-kicker">Activity ledger</p><h2 className="mt-2 text-xl font-extrabold text-white">Come si forma il saldo</h2></div><ShieldCheck className="text-[#d7b46a]" size={20} /></div><div className="mt-6 space-y-3">{activity.map(([title, amount, note]) => <div key={title} className="flex items-center gap-4 rounded-2xl border border-white/10 p-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#6f5220]/25 text-[#d7b46a]"><Check size={16} /></span><div className="min-w-0 flex-1"><p className="text-sm font-extrabold text-white">{title}</p><p className="mt-1 text-xs text-[#988795]">{note}</p></div><strong className="text-sm text-[#f1d58f]">{amount}</strong></div>)}</div></section><aside className="space-y-6"><section className="rounded-3xl border border-white/10 bg-[#120b19] p-6"><div className="flex items-center gap-3"><WalletCards className="text-[#d7b46a]" size={18} /><h2 className="font-extrabold text-white">Wallet destinatario</h2></div><p className="mt-4 text-xs leading-5 text-[#a999a6]">Collega un wallet Polygon solo per ricevere eventuali payout. Il sito non custodisce chiavi private e non chiede seed phrase.</p><input value={wallet} onChange={event => setWallet(event.target.value)} placeholder="0x..." className="mt-5 w-full rounded-2xl border border-white/10 bg-[#0b080f] px-4 py-3 text-xs text-white outline-none placeholder:text-[#81717f] focus:border-[#d7b46a]/50" /><button onClick={saveWallet} className="mt-3 w-full rounded-full bg-[#d7b46a] py-3 text-xs font-extrabold text-[#09070d] hover:bg-[#f1d58f]">{walletSaved ? "Wallet salvato" : "Salva destinazione"}</button></section><section className="rounded-3xl border border-[#d7b46a]/20 bg-gradient-to-br from-[#3b2635] to-[#120b19] p-6"><Gift className="text-[#d7b46a]" size={18} /><h2 className="mt-4 text-lg font-extrabold text-white">Riscatto simulato</h2><p className="mt-2 text-sm leading-6 text-[#b8a8b4]">Puoi prenotare la ricompensa ora. Il payout DSN on-chain resta disabilitato finché contratto, policy e controlli non sono approvati.</p><button onClick={() => setClaimed(true)} className="mt-5 w-full rounded-full border border-[#d7b46a]/50 py-3 text-xs font-extrabold text-[#f1d58f]">{claimed ? "Prenotazione registrata" : "Prenota ricompensa"}</button></section></aside></div>
    <p className="mt-8 flex items-start gap-2 text-xs leading-5 text-[#8f7f8d]"><ArrowUpRight size={14} className="mt-0.5 shrink-0 text-[#d7b46a]" /> DSN Farm è una proposta di distribuzione degli incentivi, non una promessa di rendimento. Prima di qualsiasi payout reale servono verifica del contratto, regole anti-abuso, termini, privacy, fiscalità applicabile e revisione di sicurezza.</p>
  </main></div>;
}
